env: "prod" # local, dev, prod

storage_path: "./storage/storage.db"
logger_path: "./log.log"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
  shutdown_timeout: 10s
  user: "user"

log:
  slog:
    level: "info"
    add_source: true
    format: "json"

clients:
  sso:
    address: "localhost:44044"
    timeout: 10s
    retries_count: 3
    insecure: false

app_secret: "secret"
