# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:up:
    aliases:
      - migrate
    desc: "Run database migraions"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations

  migrate:test:
    aliases:
      - migrate:test
    desc: "Run test database migraions"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
